sudo: required
services:
  - docker

branches:
  only:
    - master

before_install:
  - docker build -t $DOCKERUSER/frontend-dev -f ./web/Dockerfile.dev ./web

script:
  - docker run $DOCKERUSER/frontend-dev yarn run test:coverage

after_success:
  - docker build -t $DOCKERUSER/multi-client ./web
  - docker build -t $DOCKERUSER/multi-nginx ./nginx
  - docker build -t $DOCKERUSER/multi-server ./server
  - docker build -t $DOCKERUSER/multi-worker ./worker
  - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
  - docker push $DOCKERUSER/multi-client
  - docker push $DOCKERUSER/multi-nginx
  - docker push $DOCKERUSER/multi-server
  - docker push $DOCKERUSER/multi-worker