sudo: required
services:
  - docker

branches:
  only:
    - master

before_install:
  - docker build -f ./frontend/Dockerfile.dev -t chenanimbumba/frontend-dev ./frontend

script:
  - docker run chenanimbumba/frontend-dev yarn run test:coverage

after_success:
  - docker build -t chenanimbumba/multi-client ./frontend
  - docker build -t chenanimbumba/multi-nginx ./nginx
  - docker build -t chenanimbumba/multi-server ./server
  - docker build -t chenanimbumba/multi-worker ./worker
  - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
  - docker push chenanimbumba/multi-client
  - docker push chenanimbumba/multi-nginx
  - docker push chenanimbumba/multi-server
  - docker push chenanimbumba/multi-worker